#See https://aka.ms/containerfastmode to understand how Visual Studio uses this Dockerfile to build your images for faster debugging.

#Depending on the operating system of the host machines(s) that will build or run the containers, the image specified in the FROM statement may need to be changed.
#For more information, please see https://aka.ms/containercompat

FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build
LABEL stage=applicationdispatcherblazorserver_build
WORKDIR /src
COPY ["PDI.ApplicationDispatcher.BlazorServer/PDI.ApplicationDispatcher.BlazorServer.csproj", "PDI.ApplicationDispatcher.BlazorServer/"]
COPY ["PDI.ApplicationDispatcher.Tests/PDI.ApplicationDispatcher.Tests.csproj", "PDI.ApplicationDispatcher.Tests/"]
COPY ["PDI.ApplicationDispatcher.Controller/PDI.ApplicationDispatcher.Controller.csproj", "PDI.ApplicationDispatcher.Controller/"]
COPY ["PDI.ApplicationDispatcher.Model/PDI.ApplicationDispatcher.Model.csproj", "PDI.ApplicationDispatcher.Model/"]
COPY ["PDI.ApplicationDispatcher.Utilities/PDI.ApplicationDispatcher.Utilities.csproj", "PDI.ApplicationDispatcher.Utilities/"]
RUN dotnet restore "PDI.ApplicationDispatcher.BlazorServer/PDI.ApplicationDispatcher.BlazorServer.csproj"
COPY . .
WORKDIR "/src/PDI.ApplicationDispatcher.BlazorServer"
RUN dotnet build "PDI.ApplicationDispatcher.BlazorServer.csproj" -c Debug -o /app/build
RUN dotnet publish "PDI.ApplicationDispatcher.BlazorServer.csproj" -c Debug -o /app/publish

FROM mcr.microsoft.com/dotnet/aspnet:6.0 AS runtime
EXPOSE 80
EXPOSE 443
WORKDIR /app
COPY --from=build /app/publish .
ENTRYPOINT ["dotnet", "PDI.ApplicationDispatcher.BlazorServer.dll"]
