apiVersion: apps/v1
kind: Deployment
metadata:
  name: application-dispatcher  
spec:
  replicas: 1
  selector:
    matchLabels:
      app: application-dispatcher
  template:
    metadata:
      labels:
        app: application-dispatcher
    spec:
      containers:
      - name: application-dispatcher-blazorserver
        image: tczaplic/pdi:applicationdispatcherblazorserver
        imagePullPolicy: Always
        ports:
        - containerPort: 80
      imagePullSecrets:
      - name: docker-secret
---
apiVersion: v1
kind: Service
metadata:
  name: application-dispatcher-api
spec:
  type: NodePort
  ports:
  - port: 80
    nodePort: 30086
  selector:
    app: application-dispatcher