apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: simulationmodule-sensors  
spec:
  serviceName: "simulator"
  replicas: 1
  selector:
    matchLabels:
      app: simulationmodule-sensors
  template:
    metadata:
      labels:
        app: simulationmodule-sensors
    spec:
      containers:
      - name: simulationmodule-sensors-rest
        image: tczaplic/pdi:simulator
        imagePullPolicy: Always
        tty: true
        stdin: true
        ports:
        - containerPort: 80
      imagePullSecrets:
      - name: docker-secret
---
apiVersion: v1
kind: Service
metadata:
  name: simulationmodule-sensors-api
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 30087
  selector:
    app: simulationmodule-sensors