apiVersion: apps/v1
kind: Deployment
metadata:
  name: dataservice-vehicles  
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dataservice-vehicles
  template:
    metadata:
      labels:
        app: dataservice-vehicles
    spec:
      containers:
      - name: dataservice-vehicles-rest
        image: tczaplic/pdi:dataservicevehiclesrest
        imagePullPolicy: Always
        ports:
        - containerPort: 80
      imagePullSecrets:
      - name: docker-secret
---
apiVersion: v1
kind: Service
metadata:
  name: dataservice-vehicles-api
spec:
  type: NodePort
  ports:
  - port: 80
    nodePort: 30082
  selector:
    app: dataservice-vehicles