apiVersion: apps/v1
kind: Deployment
metadata:
  name: processingservice-sensors  
spec:
  replicas: 1
  selector:
    matchLabels:
      app: processingservice-sensors
  template:
    metadata:
      labels:
        app: processingservice-sensors
    spec:
      containers:
      - name: processingservice-sensors-rest
        image: tczaplic/pdi:processingservicesensorsrest
        imagePullPolicy: Always
        ports:
        - containerPort: 80
      imagePullSecrets:
      - name: docker-secret
---
apiVersion: v1
kind: Service
metadata:
  name: processingservice-sensors-api
spec:
  type: NodePort
  ports:
  - port: 80
    nodePort: 30088
  selector:
    app: processingservice-sensors